Convert terraform related global variables to a dictionary
cloudera-labs/cloudera.exe pull request #100
Opened 2022-03-21 21:44 UTC by jimright

After reviewing the Terraform variables with @wmudge, we agreed that changing the Terraform global variables to be a dictionary gives a better structure to the inputs. This PR makes the necessary changes to cloudera.exe to handle this structure.

Signed-off-by: Jim Enright <jenright@cloudera.com>

2022-03-21 22:33 UTC, wmudge approved these changes

2022-04-01 16:24 UTC, wmudge approved these changes

2022-04-01 16:25 UTC, wmudge requested changes
Rebase is needed

2022-04-01 16:43 UTC, jimright commented
> Rebase is needed

Should be done now.

2022-04-04 19:28 UTC, wmudge approved these changes

2022-04-04 19:28 UTC, merged