CDW Round 47
cloudera-labs/cloudera.exe pull request #102
Opened 2022-04-04 17:26 UTC by cmperro

This PR is to complete the work needed to enable (the happy path for) CDW creation and teardown.

At a high level it allows for:

- Creation of a CDW environment
- Creation of a default CDW database catalog
- Creation of non-default CDW database catalogs
- Loading demo data in non-default CDW database catalogs
- Creation of Hive and Impala VWs
- Specifying VW autoscaling min and max groups
- Specifying VW template/size
- Specifying VW tags
- Specifying Common and Application configs for VWs
- Enabling SSO for VWs
- Applying Group RBAC for VWs

It requires [CDPY PR 44](https://github.com/cloudera-labs/cdpy/pull/44)

2022-04-04 19:44 UTC, wmudge requested changes
Conflicts with this PR -- I'm guessing a rebase is in order?

2022-04-04 21:03 UTC, cmperro commented
I did one when I started this journey (~1.5 weeks ago). I’m guessing there’s been merged into devel since then?

> On Apr 4, 2022, at 3:44 PM, Webster Mudge ***@***.***> wrote:
> 
> ﻿
> @wmudge requested changes on this pull request.
> 
> Conflicts with this PR -- I'm guessing a rebase is in order?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

2022-04-21 18:58 UTC, cmperro commented
Rebase... done.

CDW CLI... back to working.

Please test!

2022-09-29 14:36 UTC, Chaffelson requested changes

2022-10-04 11:55 UTC, cmperro commented on roles/runtime/tasks/setup_aws.yml
> +    - name: Wait for CDP DW Virtual warehouses setup to complete
I hit a variant of this bug, it's why the task above that creates the VWs has a 30 second "pause".

2022-10-04 11:57 UTC, cmperro commented on roles/runtime/tasks/setup_aws.yml
> +    - name: Execute CDP Data Warehouse environment setup
I debated here... the DW terminology is to overload the term "environment": https://docs.cloudera.com/data-warehouse/cloud/aws-environments/topics/dw-activating-environments-4-data-catalogs.html

2022-10-04 11:57 UTC, cmperro commented on docs/configuration.yml
> -      os:
I don't even know why that change would have snuck in... I'll update it.

2022-10-04 11:58 UTC, cmperro commented on roles/common/defaults/main.yml
> +common__aws_vpc_id:                       "{{ infra.aws.vpc.existing.vpc_id | default('') }}"
Got it.

2022-10-04 11:59 UTC, cmperro commented on roles/runtime/tasks/initialize_teardown.yml
> +      ansible.builtin.set_fact:
Bumping this out of the block. The entire block should be skipped if there's not DW cluster.

2022-10-04 12:05 UTC, Chaffelson commented on roles/runtime/tasks/setup_aws.yml
> +    - name: Wait for CDP DW Virtual warehouses setup to complete
Would fixing the setup check to also include 'Stopped' as a valid deployment completion state fix your bug as well, and thus we could remove the pause?

2022-10-04 12:11 UTC, Chaffelson commented on roles/runtime/tasks/setup_aws.yml
> +    - name: Execute CDP Data Warehouse environment setup
I suggest we clarify by calling it 'Activate Environment for Cloudera Data Warehouse' then, if they insist on not referencing the K8s setup.

2022-10-19 13:22 UTC, cmperro commented
Comments addressed and rebase done.

2022-11-02 10:34 UTC, Chaffelson approved these changes

2022-11-15 16:29 UTC, wmudge approved these changes

2022-11-15 16:31 UTC, merged