RAZ Implementation for Azure
cloudera-labs/cloudera.exe pull request #111
Opened 2022-04-20 17:49 UTC by cmperro

This PR adds RAZ support for Azure in cloudera.exe.

- Adds a switch for enabling RAZ (bool)
- Creates a new RAZ MSI and assigns the necessary Roles to the MSI
- Updates the idbroker mapping task to pass the cloud authorizer role (RAZ)
- Updates the datalake creation task to pass the enableRAZ boolean

This PR needs to be tested in conjunction with [cloudera.cloud PR 55](https://github.com/cloudera-labs/cloudera.cloud/pull/55)

2022-05-20 17:51 UTC, wmudge requested changes
Minor changes. Needs a rebase as well.

2022-05-20 17:51 UTC, wmudge commented on roles/common/defaults/main.yml
> +common__raz_suffix:                       "{{ globals.labels.raz | default('raz') }}"
Document in `configuration.yml`

2022-05-20 17:51 UTC, wmudge commented on roles/platform/defaults/main.yml
> +plat__enable_raz:                             "{{ env.datalake.enable_raz | default(False) }}"
Document in `configuration.yml`

2022-05-20 17:51 UTC, wmudge commented on roles/platform/defaults/main.yml
> +plat__azure_raz_suffix:                       "{{ env.azure.role.label.raz | default(common__raz_suffix) }}"
Docs

2022-05-20 17:51 UTC, wmudge commented on roles/platform/defaults/main.yml
> +plat__azure_raz_identity_name:                "{{ env.azure.role.name.raz | default([plat__namespace, plat__azure_raz_suffix, plat__azure_identity_suffix] | join('-')) }}"
Docs

2022-05-20 17:51 UTC, wmudge commented on roles/platform/tasks/initialize_teardown_azure.yml
> +    role_assignment_assignee_list: "{{ msi_principal_id_list | union([plat__azure_application_service_principal_objuuid | default([])]) | list }}"
Does this return a nested list if `plat__azure_application_service_principal_objuuid` is undef?

2022-05-20 17:51 UTC, wmudge commented on roles/platform/tasks/setup_azure_authz.yml
> +  until: discovered_msi_list is subset(plat__azure_msis)
+1!

2022-06-23 08:53 UTC, Chaffelson requested changes
Still needs rebase

2022-06-23 13:01 UTC, cmperro commented
> 

Addressed requests and rebased.

2022-07-14 14:48 UTC, wmudge approved these changes

2022-11-10 13:31 UTC, Chaffelson commented
@cmperro @wmudge Can we revisit this PR please to see if we should complete it for the next release, or if it has been superceded?

2022-11-15 16:33 UTC, wmudge commented
@cmperro This needs a rebase on `devel` again, post-CDW PR merge.

2023-03-15 14:40 UTC, wmudge approved these changes

2023-03-15 14:41 UTC, merged