Add support for DFX Tech Preview
cloudera-labs/cloudera.exe pull request #12
Opened 2021-05-26 20:29 UTC by Chaffelson

Signed-off-by: Daniel Chaffelson <chaffelson@gmail.com>

2021-06-10 17:36 UTC, wmudge requested changes

2021-06-14 11:33 UTC, Chaffelson commented on roles/runtime/defaults/main.yml
> +run__df_nodes_min:                  "{{ df.min_k8s_nodes | default(3) }}"
fixed

2021-06-14 11:33 UTC, Chaffelson commented on roles/runtime/defaults/main.yml
> +run__df_nodes_max:                  "{{ df.min_k8s_nodes | default(5) }}"
fixed

2021-06-15 13:54 UTC, wmudge approved these changes

2021-06-15 13:55 UTC, merged