Extensible tagging for Cloudera Experiences
cloudera-labs/cloudera.exe pull request #48
Opened 2021-09-15 16:14 UTC by Raddish18

Enabling extensible execution of the Cloudera Experiences by use of tags.

Each experience has their own tag: ml, opdb, dh and df.

You can exclude experiences by use of "--skip-tags". For exapmle `ansible-playbook main.yml -e @examples/sandbox/config.yml -t run --skip-tags ml, opdb, dh`. This will skip the creation of ML, OpDB and the DH.

2021-10-01 08:55 UTC, Chaffelson approved these changes

2021-10-05 14:15 UTC, Raddish18 reviewed
Added Functionality for running explicit tagging for ML, DL, DW and OPDB now. e.g "-t ml" or "-t opdb" , etc.

2021-11-17 20:59 UTC, wmudge commented
Awaiting a full rebase to review the commits

2021-11-17 21:00 UTC, wmudge requested changes
Need to check the commits and the merge that is in the most recent log

2021-11-23 21:02 UTC, wmudge requested changes

2021-11-23 21:02 UTC, wmudge commented on roles/runtime/tasks/setup_base.yml
> +  cloudera.cloud.df:
revert to `df_service`

2021-11-23 21:14 UTC, Raddish18 reviewed
setup_base.yml fixed now

2021-11-23 21:42 UTC, wmudge approved these changes

2021-11-23 21:44 UTC, merged